#!/bin/bash

set -euo pipefail

TEMPLATE="${1:-readme.templ.md}"
OUT="${2:-readme.md}"
CONFIG="${3:-assets/default-config.toml}"
USAGE="${4:-assets/usage.txt}"

TMP_README=$(mktemp)

cat <<EOF >"$TMP_README"
<!--
    This file is generated by scripts/readme_gen.sh.
    Do not edit this file directly.
    Instead, edit '$TEMPLATE' and run the generator.
-->
EOF

sed -e '/{{CONFIG}}/ {
    r '"$CONFIG"'
    d
}' -e '/{{USAGE}}/ {
    r '"$USAGE"'
    d
}' "$TEMPLATE" >>"$TMP_README"

mv "$TMP_README" "$OUT"

echo "generated $OUT from $TEMPLATE"
